In [2]:
import numpy 
numpy.__version__

'1.21.5'

In [3]:
import numpy as np
np?

In [4]:
L = list(range(15))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(i) for i in L]
L2

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14']

In [8]:
type(L2[0])

str

In [12]:
L3 = [False, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [15]:
import array # Built-in Python array module
L = list(range(10))
A = array.array?
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Integer array
# np.array?
np.array([1, 4, 2, 5, 3]) # Numpy doen't need to be imported cus it hass already being imported in In [3]

array([1, 4, 2, 5, 3])

In [19]:
np.array([3.14, 1, 5, 87, 3]) # The output shows that an array can only contain one type of data-type(upcasting)


array([ 3.14,  1.  ,  5.  , 87.  ,  3.  ])

In [21]:
# The data-type can be specified by using an extra parameter 'dtype'
# Other parameters that tcan be used when creating and array are 'copy', 'order', 'subok', 'ndmin'...
np.array([1, 2, 3, 4, 5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
# NumPy arrays can be multidimensional in contrast to Python built-in array module
# This can be achieved using a nested list.
np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])