In [2]:
import numpy 
numpy.__version__

'1.21.5'

In [3]:
import numpy as np
np?

In [4]:
L = list(range(15))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(i) for i in L]
L2

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14']

In [8]:
type(L2[0])

str

In [12]:
L3 = [False, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [15]:
import array # Built-in Python array module
L = list(range(10))
A = array.array?
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Integer array
# np.array?
np.array([1, 4, 2, 5, 3]) # Numpy doen't need to be imported cus it hass already being imported in In [3]

array([1, 4, 2, 5, 3])

In [19]:
np.array([3.14, 1, 5, 87, 3]) # The output shows that an array can only contain one type of data-type(upcasting)


array([ 3.14,  1.  ,  5.  , 87.  ,  3.  ])

In [21]:
# The data-type can be specified by using an extra parameter 'dtype'
# Other parameters that tcan be used when creating and array are 'copy', 'order', 'subok', 'ndmin'...
np.array([1, 2, 3, 4, 5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [33]:
# NumPy arrays can be multidimensional in contrast to Python built-in array module
# This can be achieved using a nested list.
test_array = np.array([range(i, i + 3) for i in [2,4,6]])
test_array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [35]:
# np.dtype?
print(test_array.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [36]:
# np.zeros?
# Creates a lenght 10 integer filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
# np.ones?
# Creates a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# np.full?
# Creates a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [43]:
# Creates an array filled with a linear sequence
# Starting at 0, stopping at 20 and stepping by 2
# np.arange?
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
# np.linespace?
# Creates an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
# Creates a 3x3 array of uniformly distributed random values between 0 and 1
# np.random?
np.random.random((3,3))


array([[0.90138517, 0.93002875, 0.87486591],
       [0.29407983, 0.35593949, 0.58415625],
       [0.74926639, 0.53838735, 0.86352755]])

In [57]:
# Creates a 3x3 array of normally distributed random values with mean 0
# and standard deviation 1
#np.random.normal

np.random.normal(0, 1, (3, 3))

array([[-1.14581575, -1.34103225,  0.52881721],
       [-0.73862183,  1.66846628, -1.14092063],
       [ 1.6091181 ,  0.85977899, -0.6934349 ]])

In [60]:
# Creates a 3x3 array of random integers in the interval [0, 10]
# np.random.randint?
np.random.randint(0, 10, (3, 3))

array([[9, 7, 5],
       [0, 3, 6],
       [1, 1, 3]])

In [63]:
# Creates a 3x3 Identity matrix
# np.eye?
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.empty?