In [1]:
 import numpy as np

In [2]:
dataset = np.genfromtxt('C:/Users/Mrs. Ilemobayo/Desktop/Data_Science_Learning_Process/Datasets/normal_distribution.csv', delimiter=',')

In [3]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [4]:
print(dataset.shape) # Shape of the array
print(dataset.ndim) # Dimension of the array

(24, 8)
2


In [5]:
np.mean(dataset[0]) # Mean of the first row.

100.177647525

In [6]:
np.mean(dataset[:, 0]) # Mean of the first column

99.76743510416668

In [7]:
per_row = np.mean(dataset, axis = 1) # Mean for all rows
print(per_row)
print('\n', per_row.size)

[100.17764752  97.27899259 100.20466135 100.56785907 100.98341406
  97.83018578 101.49052285  99.75332252 101.89845125  99.77973914
 101.013081   100.54961696  98.48256886  98.49816126 101.85956927
  97.05201872 102.62147483 101.21177037  99.58777968  98.96533534
 103.85792812 101.89050288  99.07192574  99.34233101]

 24


In [8]:
per_column = np.mean(dataset, axis = 0) # mean for all columns
print(per_column)
print("\n", per_column.size)

[ 99.7674351   99.61229127 101.14584656 101.8449316   99.04871791
  99.67838931  99.7848489  100.44049274]

 8


In [9]:
np.mean(dataset)

100.16536917390624

In [11]:
print(dataset[:3])

[[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914
   98.80833412  96.81964892  98.56783189]
 [ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508
   92.65657752 105.7197853  101.23162942]
 [ 95.66253664  95.17750125  90.93318132 110.18889465  98.80084371
  105.95297652  98.37481387 106.54654286]]


In [14]:
np.mean(dataset[2]) #Mean of the third row

100.20466135250001

In [16]:
dataset[:, -1] #Last column of every row

array([ 98.56783189, 101.23162942, 106.54654286,  95.08715803,
        94.20019732, 101.13442416, 106.83273763,  92.5748759 ,
       106.03868807, 103.29147111,  95.85284217,  97.59572169,
       102.35313953,  99.58664719, 103.93383957,  98.07122664,
       104.15899829, 104.70526438,  99.92159953, 102.20618501,
        98.00253006,  94.76253572, 103.83852459, 100.07721494])

In [23]:
dataset[:, :3] # First 3 colmuns of every row

array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132],
       [ 91.37294597, 100.96781394, 100.40118279],
       [101.20862522, 103.5730309 , 100.28690912],
       [102.80387079,  98.29687616,  93.24376389],
       [106.71751618, 102.97585605,  98.45723272],
       [ 96.02548256, 102.82360856, 106.47551845],
       [105.30350449,  92.87730812, 103.19258339],
       [110.44484313,  93.87155456, 101.5363647 ],
       [101.3514185 , 100.37372248, 106.6471081 ],
       [ 97.21315663, 107.02874163, 102.17642112],
       [ 95.65982034, 107.22482426, 107.19119932],
       [100.39303522,  92.0108226 ,  97.75887636],
       [103.1521596 , 109.40523174,  93.83969256],
       [106.11454989,  88.80221141,  94.5081787 ],
       [ 96.78266211,  99.84251605, 104.03478031],
       [101.86186193, 103.61720152,  99.57859892],
       [ 97.49594839,  96.59385486, 104.63817694],
       [ 96.76814836,  91.67792

In [24]:
np.median(dataset[-1])

99.18748092

In [27]:
np.mean(dataset, axis = 1)

array([100.17764752,  97.27899259, 100.20466135, 100.56785907,
       100.98341406,  97.83018578, 101.49052285,  99.75332252,
       101.89845125,  99.77973914, 101.013081  , 100.54961696,
        98.48256886,  98.49816126, 101.85956927,  97.05201872,
       102.62147483, 101.21177037,  99.58777968,  98.96533534,
       103.85792812, 101.89050288,  99.07192574,  99.34233101])

In [28]:
np.var(dataset, axis = 0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])