In [4]:
import numpy as np

In [54]:
# np.random?
# np.random.seed?
np.random.seed(0) # seed for reproducibility.

x1 = np.random.randint(10, size=6) # One-dimensional array (a 1x6 array)
x2 = np.random.randint(10, size=(3,4)) # Two-Dimensional array (a 3x4 array)
x3 = np.random.randint(10, size=(3, 4, 5)) # Three dimensional array (three of a 4x5 array)

# 1x6 array means 1 row 6 columns

In [29]:
# ATTRIBUTES OF AN ARRAY BELOW!!!

In [24]:
print('x3 ndim: ', x3.ndim) # ndim -- Number of dimensions
print('x3 shape: ', x3.shape) # shape -- The size of each dimension
print('x3 size: ', x3.size) # size -- The total size of the array


x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [25]:
print("dtype:", x3.dtype) # dtype -- Data type of the array 

dtype: int32


In [26]:
print("itemsize:", x3.itemsize, "bytes") # itemsize -- The size of each element in the array in bytes.
print("nbytes:", x3.nbytes, "bytes") # nbytes -- The total size of the whole array in bytes.

itemsize: 4 bytes
nbytes: 240 bytes


In [28]:
# The size of the whole array can be said to be the product of the itemsize and size

In [ ]:
 # ARRAY INDEXING

In [30]:
x1 # Indexing in a one dimensional array

array([5, 0, 3, 3, 7, 9])

In [32]:
x1[0]

5

In [38]:
x1[4]

7

In [39]:
x1[-1]

9

In [40]:
x2 # Indexing ina two dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0,0]

3

In [42]:
x2[2,0]

1

In [43]:
x2[2, -1]

7

In [44]:
# Setting/Changing a value in an array

In [50]:
print(x1)
x1[0] = 2

print(x1)

[5 0 3 3 7 9]
[2 0 3 3 7 9]


In [55]:
print(x2)
x2[1,2] = 6

print("\n")

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[3 5 2 4]
 [7 6 6 8]
 [1 6 7 7]]
