In [4]:
import numpy as np

In [5]:
# np.random?
# np.random.seed?
np.random.seed(0) # seed for reproducibility.

x1 = np.random.randint(10, size=6) # One-dimensional array (a 1x6 array)
x2 = np.random.randint(10, size=(3,4)) # Two-Dimensional array (a 3x4 array)
x3 = np.random.randint(10, size=(3, 4, 5)) # Three dimensional array (three of a 4x5 array)

print(x1,"\n")
print(x2,"\n")
print(x3)
# 1x6 array means 1 row 6 columns

[5 0 3 3 7 9] 

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [6]:
# ATTRIBUTES OF AN ARRAY BELOW!!!

In [15]:
print('x3 ndim: ', x3.ndim) # ndim -- Number of dimensions
print('x3 shape: ', x3.shape) # shape -- The size of each dimension
print('x3 size: ', x3.size) # size -- The total size of the array


x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [8]:
print("dtype:", x3.dtype) # dtype -- Data type of the array 

dtype: int32


In [9]:
print("itemsize:", x3.itemsize, "bytes") # itemsize -- The size of each element in the array in bytes.
print("nbytes:", x3.nbytes, "bytes") # nbytes -- The total size of the whole array in bytes.

itemsize: 4 bytes
nbytes: 240 bytes


In [10]:
# The size of the whole array can be said to be the product of the itemsize and size

In [11]:
 # ARRAY INDEXING

In [16]:
x1 # Indexing in a one dimensional array

array([5, 0, 3, 3, 7, 9])

In [17]:
x1[0]

5

In [19]:
x1[4]

7

In [20]:
x1[-2]

7

In [6]:
x2 # Indexing ina two dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x2[0]

array([3, 5, 2, 4])

In [13]:
x2[0:2,0:2]

array([[3, 5],
       [7, 6]])

In [19]:
x2[2, -1]

7

In [20]:
# Setting/Changing a value in an array

In [21]:
print(x1)
x1[0] = 2

print(x1)

[5 0 3 3 7 9]
[2 0 3 3 7 9]


In [22]:
print(x2)
x2[1,2] = 6

print("\n")

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[3 5 2 4]
 [7 6 6 8]
 [1 6 7 7]]


In [23]:
# ARRAY SLICING

In [27]:
x = np.arange(10)
x
# SLICING ONE DIMENSIONAL ARRAY

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:4] # for the first 4 elemets

array([0, 1, 2, 3])

In [30]:
x[4:] # elements after element 4

array([4, 5, 6, 7, 8, 9])

In [31]:
x[3:7] # middle subarray

array([3, 4, 5, 6])

In [34]:
print(x)
x[::2] # every other element

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [29]:
x[1::2] # every other element

array([1, 3, 5, 7, 9])

In [50]:
x[::-1] # all elements of the array reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [67]:
# SLICING 2 DIMENSIONAL ARRAY
x2 = np.random.randint(20, size=(3,3))
x2

array([[14,  9,  1],
       [ 4, 10, 11],
       [ 8, 11,  2]])

In [69]:
x2[:2, :2] # The parameters follow row and colomn respectively.
           # Two rows, two columns

array([[14,  9],
       [ 4, 10]])

In [70]:
x2[:2, ::2]  # for the second row and every other column

array([[14,  1],
       [ 4, 11]])

In [71]:
x2[::-1, ::-1] # reversing subarray dimensions

array([[ 2, 11,  8],
       [11, 10,  4],
       [ 1,  9, 14]])

In [88]:
print(x2[:, 0]) # first column of the array


[14  4  8]


In [89]:
print(x2[0]) # first row of the array


[14  9  1]


In [38]:
print(x2)

[[3 5 2 4]
 [7 6 6 8]
 [1 6 7 7]]


In [63]:
x2_sub = (x2[:2, :2]) # A slice of array x2 was created
print(x2_sub)

[[ 2  2]
 [ 3 18]]


In [64]:
x2_sub[0, 0] = 99 # The value of the first element got changed
print(x2_sub)

[[99  2]
 [ 3 18]]


In [65]:
print(x2) # But the original array got changed also 

[[99  2  3]
 [ 3 18 14]
 [ 3 17 18]]


In [44]:
# Slicing an array returns a veiw rather than a copy of the array
# This can be advantageous when handling large data. It allows
# for the editing of pieces of the the dataset without needing to 
# copy the piece... But can be disadvantageous in a case when                                                                                                                                              gbgggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbgggggggggggggggggggggggygy+gyygyggggggggggggggggggggggg++-+gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg+++++g+++++g++ggggggggggggggggggggggggggggggg+gggggg+g+++++
# copying a piece of the dataset is what was intended and then
# end up modifying the whole dataset.

In [45]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [46]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [47]:
print(x2)

[[99  5  2  4]
 [ 7  6  6  8]
 [ 1  6  7  7]]


In [48]:
# RESHAPING OF ARRAYS

In [49]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
grid = np.arange(1,10).reshape(3,3) # The reshape() method can be used to reshape the structure of an array.
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [52]:
x.reshape((3, 1)) # Using the reshape method


array([[1],
       [2],
       [3]])

In [53]:
x[:, np.newaxis] # using the newaxis keyword

array([[1],
       [2],
       [3]])

In [54]:
# CONCATENATION AND SPLITTING OF ARRAYS

In [55]:
# Concatenation of one dimensional arrays

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [61]:
z = np.array([99, 99, 99])

result = np.concatenate([x, x, z])
result

array([ 1,  2,  3,  1,  2,  3, 99, 99, 99])

In [57]:
# Concatenation of two dimensional arrays

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [62]:
# Concatenating along the first axis 
np.concatenate([grid, grid], axis=0) # Zero-indexed

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
# Concatenating along the second axis 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
# Concatenating arrays of different dimensional. 

y = np.array([1, 2, 3])
np.vstack([y, grid]) # row-wise
# np.vstack([grid, y])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
x = np.array([[9], 
              [9]])
np.hstack([x, grid]) # Column-wise
# np.hstack?
# print(grid)



array([[9, 1, 2, 3],
       [9, 4, 5, 6]])

In [79]:
# SPLITTING OF ARRAYS
# .split is mainly used for one dimensional arrays WHILE
# .vsplt and .hsplit are used for multidimensional arrays
# Using .spilt,  N split pounts leads to N + 1 subarrays

In [80]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x,[3, 5])

print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [81]:
grid1 = np.arange(16).reshape(4, 4)
grid1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
upper, lower = np.vsplit(grid1, [2])
print(upper) 
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [87]:
left, right = np.hsplit(grid1, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
