In [1]:
import numpy as np

In [4]:
# np.random?
# np.random.seed?
np.random.seed(0) # seed for reproducibility.

x1 = np.random.randint(10, size=6) # One-dimensional array (a 1x6 array)
x2 = np.random.randint(10, size=(3,4)) # Two-Dimensional array (a 3x4 array)
x3 = np.random.randint(10, size=(3, 4, 5)) # Three dimensional array (three of a 4x5 array)

print(x1,"\n")
print(x2,"\n")
print(x3)
# 1x6 array means 1 row 6 columns

[5 0 3 3 7 9] 

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [6]:
# ATTRIBUTES OF AN ARRAY BELOW!!!

In [5]:
print('x3 ndim: ', x3.ndim) # ndim -- Number of dimensions
print('x3 shape: ', x3.shape) # shape -- The size of each dimension
print('x3 size: ', x3.size) # size -- The total size of the array


x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [6]:
print("dtype:", x3.dtype) # dtype -- Data type of the array 

dtype: int64


In [7]:
print("itemsize:", x3.itemsize, "bytes") # itemsize -- The size of each element in the array in bytes.
print("nbytes:", x3.nbytes, "bytes") # nbytes -- The total size of the whole array in bytes.

itemsize: 8 bytes
nbytes: 480 bytes


In [8]:
# The size of the whole array can be said to be the product of the itemsize and size

In [9]:
 # ARRAY INDEXING

In [10]:
x1 # Indexing in a one dimensional array

array([5, 0, 3, 3, 7, 9])

In [11]:
x1[0]

5

In [12]:
x1[4]

7

In [13]:
x1[-2]

7

In [14]:
x2 # Indexing ina two dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0]

array([3, 5, 2, 4])

In [16]:
x2[0:2,0:2]

array([[3, 5],
       [7, 6]])

In [17]:
x2[2, -1]

7

In [18]:
# Setting/Changing a value in an array

In [19]:
print(x1)
x1[0] = 2

print(x1)

[5 0 3 3 7 9]
[2 0 3 3 7 9]


In [20]:
print(x2)
x2[1,2] = 6

print("\n")

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[3 5 2 4]
 [7 6 6 8]
 [1 6 7 7]]


In [21]:
# ARRAY SLICING

In [22]:
x = np.arange(10)
x
# SLICING ONE DIMENSIONAL ARRAY

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:4] # for the first 4 elemets

array([0, 1, 2, 3])

In [24]:
x[4:] # elements after element 4

array([4, 5, 6, 7, 8, 9])

In [25]:
x[3:7] # middle subarray

array([3, 4, 5, 6])

In [26]:
print(x)
x[::2] # every other element

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [27]:
x[1::2] # every other element

array([1, 3, 5, 7, 9])

In [28]:
x[::-1] # all elements of the array reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [30]:
# SLICING 2 DIMENSIONAL ARRAY
x2 = np.random.randint(20, size=(3,3))
x2

array([[15,  3, 12],
       [ 4,  8, 14],
       [15,  3, 15]])

In [31]:
x2[:2, :2] # The parameters follow row and colomn respectively.
           # Two rows, two columns

array([[15,  3],
       [ 4,  8]])

In [32]:
x2[:2, ::2]  # for the second row and every other column

array([[15, 12],
       [ 4, 14]])

In [33]:
x2[::-1, ::-1] # reversing subarray dimensions

array([[15,  3, 15],
       [14,  8,  4],
       [12,  3, 15]])

In [34]:
print(x2[:, 0]) # first column of the array


[15  4 15]


In [35]:
print(x2[0]) # first row of the array


[15  3 12]


In [36]:
print(x2)

[[15  3 12]
 [ 4  8 14]
 [15  3 15]]


In [37]:
x2_sub = (x2[:2, :2]) # A slice of array x2 was created
print(x2_sub)

[[15  3]
 [ 4  8]]


In [38]:
x2_sub[0, 0] = 99 # The value of the first element got changed
print(x2_sub)

[[99  3]
 [ 4  8]]


In [39]:
print(x2) # But the original array got changed also 

[[99  3 12]
 [ 4  8 14]
 [15  3 15]]


In [40]:
# Slicing an array returns a veiw rather than a copy of the array
# This can be advantageous when handling large data. It allows
# for the editing of pieces of the the dataset without needing to 
# copy the piece... But can be disadvantageous in a case when                                                                                                                                              gbgggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbgggggggggggggggggggggggygy+gyygyggggggggggggggggggggggg++-+gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg+++++g+++++g++ggggggggggggggggggggggggggggggg+gggggg+g+++++
# copying a piece of the dataset is what was intended and then
# end up modifying the whole dataset.

In [41]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)	

[[99  3]
 [ 4  8]]


In [42]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  3]
 [ 4  8]]


In [43]:
print(x2) 

[[99  3 12]
 [ 4  8 14]
 [15  3 15]]


In [44]:
# RESHAPING OF ARRAYS

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
grid = np.arange(1,10).reshape(3,3) # The reshape() method can be used to reshape the structure of an array.
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [48]:
x.reshape((3, 1)) # Using the reshape method


array([[1],
       [2],
       [3]])

In [49]:
x[:, np.newaxis] # using the newaxis keyword

array([[1],
       [2],
       [3]])

In [50]:
# CONCATENATION AND SPLITTING OF ARRAYS

In [51]:
# Concatenation of one dimensional arrays

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [52]:
z = np.array([99, 99, 99])

result = np.concatenate([x, x, z])
result

array([ 1,  2,  3,  1,  2,  3, 99, 99, 99])

In [53]:
# Concatenation of two dimensional arrays

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [54]:
# Concatenating along the first axis 
np.concatenate([grid, grid], axis=0) # Zero-indexed

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
# Concatenating along the second axis 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
# Concatenating arrays of different dimensional. 

y = np.array([1, 2, 3])
np.vstack([y, grid]) # row-wise
# np.vstack([grid, y])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
x = np.array([[9], 
              [9]])
np.hstack([x, grid]) # Column-wise
# np.hstack?
# print(grid)



array([[9, 1, 2, 3],
       [9, 4, 5, 6]])

In [58]:
# SPLITTING OF ARRAYS
# .split is mainly used for one dimensional arrays WHILE
# .vsplt and .hsplit are used for multidimensional arrays
# Using .spilt,  N split pounts leads to N + 1 subarrays

In [59]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x,[3, 5]) # [3, 5]: [:3, 3:5, 5:]

print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [60]:
grid1 = np.arange(16).reshape(4, 4)
grid1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
upper, lower = np.vsplit(grid1, [2])
print(upper) 
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [62]:
left, right = np.hsplit(grid1, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [63]:
import numpy as np
np.var?

Signature:      
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.var(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function var at 0x795249ec00>
File:            /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/numpy/core/fromnumeric.py
Docstring:      
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of the flattened array.

    .. versionadded:: 1.7

In [64]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [65]:
x = np.arange(10)
x[5::-2]

array([5, 3, 1])

In [66]:
array = np.array([range (i, i+3) for i in [3 ,12, 20]])
array

array([[ 3,  4,  5],
       [12, 13, 14],
       [20, 21, 22]])

In [67]:
array[:4, :2]

array([[ 3,  4],
       [12, 13],
       [20, 21]])

In [ ]:
# Splitting an array

In [17]:
np.hsplit(array, (3))

[array([[ 3],
        [12],
        [20]]),
 array([[ 4],
        [13],
        [21]]),
 array([[ 5],
        [14],
        [22]])]

In [16]:
np.vsplit(array, (3))

[array([[3, 4, 5]]), array([[12, 13, 14]]), array([[20, 21, 22]])]

In [18]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000023C465B79C0>
File:            c:\users\mrs. ilemobayo\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]

In [22]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x0000023C465B77E0>
File:            c:\users\mrs. ilemobayo\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned 

In [3]:
# Fancy Indexing

rand = np.random.RandomState(42)
x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [4]:
# Fancy Indexing can be done by either passing  an array of the indices of the elements.
[x[3], x[7], x[2]]

[71, 86, 14]

In [5]:
# Or pass a list containing tge indeces of the specific elements needed.
ind = [3, 7, 2]
x[ind]

array([71, 86, 14])