In [4]:
import numpy as np

In [54]:
# np.random?
# np.random.seed?
np.random.seed(0) # seed for reproducibility.

x1 = np.random.randint(10, size=6) # One-dimensional array (a 1x6 array)
x2 = np.random.randint(10, size=(3,4)) # Two-Dimensional array (a 3x4 array)
x3 = np.random.randint(10, size=(3, 4, 5)) # Three dimensional array (three of a 4x5 array)

# 1x6 array means 1 row 6 columns

In [29]:
# ATTRIBUTES OF AN ARRAY BELOW!!!

In [24]:
print('x3 ndim: ', x3.ndim) # ndim -- Number of dimensions
print('x3 shape: ', x3.shape) # shape -- The size of each dimension
print('x3 size: ', x3.size) # size -- The total size of the array


x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [25]:
print("dtype:", x3.dtype) # dtype -- Data type of the array 

dtype: int32


In [26]:
print("itemsize:", x3.itemsize, "bytes") # itemsize -- The size of each element in the array in bytes.
print("nbytes:", x3.nbytes, "bytes") # nbytes -- The total size of the whole array in bytes.

itemsize: 4 bytes
nbytes: 240 bytes


In [28]:
# The size of the whole array can be said to be the product of the itemsize and size

In [ ]:
 # ARRAY INDEXING

In [30]:
x1 # Indexing in a one dimensional array

array([5, 0, 3, 3, 7, 9])

In [32]:
x1[0]

5

In [38]:
x1[4]

7

In [39]:
x1[-1]

9

In [40]:
x2 # Indexing ina two dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0,0]

3

In [42]:
x2[2,0]

1

In [43]:
x2[2, -1]

7

In [44]:
# Setting/Changing a value in an array

In [50]:
print(x1)
x1[0] = 2

print(x1)

[5 0 3 3 7 9]
[2 0 3 3 7 9]


In [55]:
print(x2)
x2[1,2] = 6

print("\n")

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[3 5 2 4]
 [7 6 6 8]
 [1 6 7 7]]


In [56]:
# ARRAY SLICING

In [58]:
x = np.arange(10)
x
# SLICING ONE DIMENSIONAL ARRAY

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[:5] # for the forst 5 elemets

array([0, 1, 2, 3, 4])

In [60]:
x[5:] # elements after element 5

array([5, 6, 7, 8, 9])

In [65]:
x[3:7] # middle subarray

array([3, 4, 5, 6])

In [66]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [67]:
x[1::2] # every other element

array([1, 3, 5, 7, 9])

In [68]:
x[::-1] # all elements of the array reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [69]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [70]:
# SLICING 2 DIMENSIONAL ARRAY
x2

array([[3, 5, 2, 4],
       [7, 6, 6, 8],
       [1, 6, 7, 7]])

In [71]:
x2[:2, :3] # The parameters follow row and colomn respectively.
           # Two rows, three columns

array([[3, 5, 2],
       [7, 6, 6]])

In [89]:
x2[:3, ::2]  # all rows, every other column

array([[3, 2],
       [7, 6],
       [1, 7]])

In [90]:
x2[::-1, ::-1] # reversing subarray dimensions

array([[7, 7, 6, 1],
       [8, 6, 6, 7],
       [4, 2, 5, 3]])

In [91]:
print(x2[:, 0]) # first column of the array

[3 7 1]


In [94]:
print(x2[0, :]) # first row of the array
# print(x2[0]) # Another form to perform same operation.

[3 5 2 4]


In [95]:
print(x2)

[[3 5 2 4]
 [7 6 6 8]
 [1 6 7 7]]


In [99]:
x2_sub = (x2[:2, :2]) # A slice of array x2 was created
print(x2_sub)

[[3 5]
 [7 6]]


In [100]:
x2_sub[0, 0] = 99 # The value of the first element got changed
print(x2_sub)

[[99  5]
 [ 7  6]]


In [101]:
print(x2) # But the original array got changed also 

[[99  5  2  4]
 [ 7  6  6  8]
 [ 1  6  7  7]]


In [ ]:
# Slicing an array returns a veiw rather than a copy of the array
# This can be advantageous when handling large data. It allows
# for the editing of pieces of the the dataset without needing to 
# copy the piece... But can be disadvantageous in a case 