In [2]:
import numpy as np
np.random.seed(0)

In [3]:
def compute_reciprocal(values):
    """Function to compute the reciprocal of all elements in a given array"""
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [4]:
values = np.random.randint(1, 10, size = 5) #geneates an array of five elements within range 1 -10.
compute_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
#But this process is slow....

In [12]:
#big_array = np.random.randint(1, 100, size = 1000000)
#%timeit compute_reciprocal(big_array)

In [7]:
%timeit (1.0 / big_array)

18.6 ms ± 1.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
# Numpy's UFuncs allows for the operation of all arithmetics on an array
# Instead of writing a function to iterate the process for all elements 
# in the array which is much slower.
# It can be unary UFuncs(for one input) and 
# binary UFuncs(for two inputs)

In [9]:
x = np.arange(7)
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.negative(x))
print(np.multiply(x, 5))
print(np.divide(x, 5))
print(np.floor_divide(x, 5))
print(np.power(x, 5))
print(np.mod(x, 2))

[ 5  6  7  8  9 10 11]
[-5 -4 -3 -2 -1  0  1]
[ 0 -1 -2 -3 -4 -5 -6]
[ 0  5 10 15 20 25 30]
[0.  0.2 0.4 0.6 0.8 1.  1.2]
[0 0 0 0 0 1 1]
[   0    1   32  243 1024 3125 7776]
[0 1 0 1 0 1 0]


In [10]:
# The absolute valie of an array can also be found either gy
# using numpy's ufuncs or python's native func.

In [11]:
print(abs(x)) # python's native 
print(np.absolute(x)) # Numpy's UFunc

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]


In [13]:
np.pi?

Type:        float
String form: 3.141592653589793
Docstring:   Convert a string or number to a floating point number, if possible.

In [ ]:
# Trigonometric UFuncs

In [14]:
theta = np.linspace(0, np.pi, 3)	

In [ ]:
print("theta =", theta)
print("sin theta =", np.sin(theta))
print("cos theta =", np.cos(theta))
print("tan theta =", np.ta