In [30]:
import numpy as np
np.random.seed(0)

In [2]:
def compute_reciprocal(values):
    """Function to compute the reciprocal of all elements in a given array"""
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [3]:
values = np.random.randint(1, 10, size = 5) #geneates an array of five elements within range 1 -10.
compute_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
#But this process is slow....

In [5]:
#big_array = np.random.randint(1, 100, size = 1000000)
#%timeit compute_reciprocal(big_array)

In [6]:
#%timeit (1.0 / big_array)

In [7]:
# Numpy's UFuncs allows for the operation of all arithmetics on an array
# Instead of writing a function to iterate the process for all elements 
# in the array which is much slower.
# It can be unary UFuncs(for one input) and 
# binary UFuncs(for two inputs)

In [8]:
x = np.arange(7)
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.negative(x))
print(np.multiply(x, 5))
print(np.divide(x, 5))
print(np.floor_divide(x, 5))
print(np.power(x, 5))
print(np.mod(x, 2))

[ 5  6  7  8  9 10 11]
[-5 -4 -3 -2 -1  0  1]
[ 0 -1 -2 -3 -4 -5 -6]
[ 0  5 10 15 20 25 30]
[0.  0.2 0.4 0.6 0.8 1.  1.2]
[0 0 0 0 0 1 1]
[   0    1   32  243 1024 3125 7776]
[0 1 0 1 0 1 0]


In [9]:
# The absolute valie of an array can also be found either gy
# using numpy's ufuncs or python's native func.

In [10]:
print(abs(x)) # python's native 
print(np.absolute(x)) # Numpy's UFunc

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]


In [11]:
np.pi?

Type:        float
String form: 3.141592653589793
Docstring:   Convert a string or number to a floating point number, if possible.

In [12]:
# Trigonometric UFuncs

In [13]:
theta = np.linspace(0, np.pi, 3)	

In [14]:
print("theta =", theta)
print("sin theta =", np.sin(theta))
print("cos theta =", np.cos(theta))
print("tan theta =", np.tan(theta))	

theta = [0.         1.57079633 3.14159265]
sin theta = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos theta = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan theta = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [15]:
# Exponential and logarithm UFuncs

In [16]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))
print("x^3 =", np.power(x, 3))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
x^3 = [ 1  8 27]


In [17]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [18]:
# Storing the output of a particular UFuncs directly into
# a specific memory location
# This does not make any difference in small computations
# But when handling very large arrays a lot of memory is saved by directin
# the output to the specific  memory location

In [19]:
x = np.arange(5)
y = np.empty(5)
np.multiply(2, x, out=y) # The "out" parameter is used to dore
print(y)

[0. 2. 4. 6. 8.]


In [20]:
b = np.zeros(10)
np.power(2, x, out=b[::2])
print(b)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [21]:
# .reduce() vs .accumulate()

In [22]:
# .reduce() is used to perform an operation repeatitively on the elements of an
# array until one single result remains.

# .accumulate() is used to perform an operation repeatitively on the elements
# of an array but unlike .reduce() it also shows the intermediate computations
# before getting the final result.

In [23]:
array_1 = np.arange(1, 6)
np.add.reduce(array_1)

15

In [24]:
np.add.accumulate(array_1)

array([ 1,  3,  6, 10, 15])

In [25]:
# .accumulate() work for .add and .prod
# It also works like .cumsum() and .cumprod()

In [26]:
# np.outer()
# This UFunc is used to perform product on one array using the elements
# of another array. It is similar to Matrix multiplication.

# The operation can also be changed i.e np.add.outer() performs addition
# instead of multiplication.

In [27]:
z = [1, 2, 3, 4, 5]
k = [4, 5]
np.outer(z, k)

array([[ 4,  5],
       [ 8, 10],
       [12, 15],
       [16, 20],
       [20, 25]])

In [28]:
np.add.outer(z, k)

array([[ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [36]:
big_array_2 = np.random.random(10000)

In [37]:
%timeit sum(big_array_2)

2.36 ms ± 35.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [38]:
%timeit np.sum(big_array_2)  # numpy's sum function runs faster

18 μs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [40]:
np.min(big_array_2), np.max(big_array_2)  # minimum and maximum of the elements in an array

(7.2449638492178e-05, 0.9999779517807228)