In [110]:
import numpy as np

In [12]:
def selection_sort(x):
    for i in range(len(x)): 
        swap = i + np.argmin(x[i:]) 
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [66]:
x = np.array([2, 1, 3, 5, 4])
# selection_sort(x)

In [68]:
np.sort(x) 


array([1, 2, 3, 4, 5])

In [74]:
i = np.argsort(x) # Shows the indices of the sorted elements
x[i]

array([1, 2, 3, 4, 5])

In [75]:
rand =  np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [81]:
 #Using np.sort() axis parameter

print(np.sort(x, axis=0)) # Sorting the columns. 
print(np.sort(x, axis=1)) # Sorting the rows. 

[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [118]:
# Partioning
X = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(X, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [131]:
np.partition(x, 3, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [2, 1, 4, 5, 7, 7],
       [0, 4, 1, 5, 9, 5]])

In [95]:
np.partition??


Signature:       np.partition(a, kth, axis=-1, kind='introselect', order=None)
Call signature:  np.partition(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function partition at 0x000001667F69F240>
File:            c:\users\astrojoe\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Source:         
@array_function_dispatch(_partition_dispatcher)
def partition(a, kth, axis=-1, kind='introselect', order=None):
    """
    Return a partitioned copy of an array.

    Creates a copy of the array with its elements rearranged in such a
    way that the value of the element in k-th position is in the position
    the value would be in a sorted array.  In the partitioned array, all
    elements before the k-th element are less than or equal to that
    element, and all the elements after the k-th element are greater than
    or equal to that element.  The ordering of the elements in the two
    partitions is undefined.

    .. versionadded:: 1.8.0

    Paramete

In [130]:
import numpy as np

# Simulate 1 million patient wait times (in minutes)
wait_times = np.random.randint(1, 300, size=1_000_000)

# Median index
mid = len(wait_times) // 2

# Using np.partition
%timeit np.partition(wait_times, mid)[mid]

# Using full sort
%timeit np.sort(wait_times)[mid]


24 ms ± 314 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
97.9 ms ± 2.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
