In [4]:
import numpy as np

In [12]:
def selection_sort(x):
    for i in range(len(x)): 
        swap = i + np.argmin(x[i:]) 
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [66]:
x = np.array([2, 1, 3, 5, 4])
# selection_sort(x)

In [68]:
np.sort(x) 


array([1, 2, 3, 4, 5])

In [74]:
i = np.argsort(x) # Shows the indices of the sorted elements
x[i]

array([1, 2, 3, 4, 5])

In [75]:
rand =  np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [81]:
 #Using np.sort() axis parameter

print(np.sort(x, axis=0)) # Sorting the columns. 
print(np.sort(x, axis=1)) # Sorting the rows. 

[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [83]:
# Partioning
X = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(X, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [93]:
np.partition(x, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])