In [1]:
import numpy as np 

In [2]:
# Structured Numpy Arrays
# Normal NUmpy arrays do not allow for heterogeneous datd, but these numpy 
# structured arrays can contain heterogeneous data types. 

# If you want to store certain info about a group of ppl 
name = ['Alice', 'Bob', 'Cathy', 'Dough']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

# These info can be contained in one array using;
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)
print('\n')
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


In [3]:
data['name'] = name
data['age'] = age 
data['weight'] = weight 
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Dough', 19, 61.5)]


In [4]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Dough'], dtype='<U10')

In [5]:
data[0]

('Alice', 25, 55.)

In [6]:
data[-1]['name']

'Dough'

In [7]:
# Get names where age is under 30

data[data['age'] < 30]['name']

array(['Alice', 'Dough'], dtype='<U10')

In [14]:
# Different ways of creating a structured array

# The dictionary method, which was used earlier
np.dtype({'names':('name', 'age', 'weight'),
         'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [18]:
# Using Python types or Numpy dtypes
np.dtype({'names':('name', 'age', 'weight'), 
          'formats':((np.str_, 10), int, np.float64)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [20]:
# As a list of tuples 
np.dtype([('names', 'U10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('names', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [21]:
# Numpy data types 
# 'b' Byte np.dtype('b')
# 'i' Signed integer np.dtype('i4') == np.int32
# 'u' Unsigned integer np.dtype('u1') == np.uint8
# 'f' Floating point np.dtype('f8') == np.int64
# 'c' Complex floating point np.dtype('c16') == np.complex128
# 'S', 'a' string np.dtype('S5')
# 'U' Unicode string np.dtype('U') == np.str_
# 'V' Raw data (void) np.dtype('V') == np.void

In [25]:
# A more complex example

tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3,3))])
X = np.zeros(1, dtype=tp)
print(X)
print(X['mat'][0])

[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# Record Arrays
# This allows to access fields as attribute(e.g var.field) rather than as 
# dictionary(e.g var[field]). This makes code look cleaner.
# This is done using the .veiw(np.recarrray)
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])