In [3]:
import numpy as np

print(np.__version__)

2.3.2


In [43]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
array_1 = np.full((3,3), True, dtype=bool)
array_1


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [36]:
arr_odd = arr[1::2]
arr_odd

array([1, 3, 5, 7, 9])

In [41]:
# arr[arr%2 == 1] = -1
arr[1::2] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
arr_copy = arr.copy()
arr_copy[1::2] = -1
print(arr_copy)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# arr.reshape(2,5)
arr.reshape(2, -1) # -1 automatically decides the number of columns 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [84]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [97]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [99]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Returns elements by comparing a to b
np.where(a == b) 

(array([1, 3, 5, 7]),)

In [115]:
# Printin out elements in the array between 5 and 10

a = np.array([2, 6, 1, 9, 10, 3, 27]) 
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [116]:
# Reversing the rows of a 2d array

arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [117]:
# Reversing the columns of a 2d array 

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [123]:
# Produces an array of floats betweena particular range and array size

np.random.uniform(5, 10, size=(5,3))

array([[5.47009746, 7.57871893, 6.93354436],
       [7.2901424 , 6.32804078, 8.18423904],
       [7.04879823, 5.22588155, 8.85460759],
       [7.76887908, 6.3744401 , 7.20918978],
       [5.97756339, 7.01879372, 8.51483174]])

In [137]:
# Round elements of an array to 3 decimal places 
# rand_arr = np.random.random((5,3)).round(3)

rand_arr = np.random.random((5,3))
np.set_printoptions(precision= 3)
rand_arr

array([[0.796, 0.792, 0.136],
       [0.73 , 0.297, 0.019],
       [0.442, 0.024, 0.513],
       [0.075, 0.685, 0.936],
       [0.659, 0.647, 0.015]])

In [133]:
# Determines the way floating point numberes, arrays, and other Numpy objects 
# are displayed

np.set_printoptions?

Signature:
np.set_printoptions(
    precision=None,
    threshold=None,
    edgeitems=None,
    linewidth=None,
    suppress=None,
    nanstr=None,
    infstr=None,
    formatter=None,
    sign=None,
    floatmode=None,
    *,
    legacy=None,
    override_repr=None,
)
Docstring:
Set printing options.

These options determine the way floating point numbers, arrays and
other NumPy objects are displayed.

Parameters
----------
precision : int or None, optional
    Number of digits of precision for floating point output (default 8).
    May be None if `floatmode` is not `fixed`, to print as many digits as
    necessary to uniquely specify the value.
threshold : int, optional
    Total number of array elements which trigger summarization
    rather than full repr (default 1000).
    To always use the full repr without summarization, pass `sys.maxsize`.
edgeitems : int, optional
    Number of array items in summary at beginning and end of
    each dimension (default 3).
linewidth : int, opt

In [29]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=10)
rand_arr

array([[0.0005434049, 0.0002783694, 0.0004245176],
       [0.0008447761, 0.0000047189, 0.0001215691],
       [0.0006707491, 0.0008258528, 0.0001367066]])

In [38]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where(np.logical_and(a >= 5, a <= 10))
# np.where() - returns the index of elements that satisfies a condition.a
# np.logical_and - &
a[index]
        
        

array([ 6,  9, 10])

In [50]:
def maxx(x, y):
    """Get the max of two items"""
    if x >= y:
        return x
    else: 
        return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

# np.vectorize() vectorizes a functon which takes arrays and returns one array 
# based on the workings of the 'vectorized' function 
pair_maxx = np.vectorize(maxx, otypes=[float])
pair_maxx(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [ ]:
np.vect